// State identity. A state is the normalized route plus an abstraction of the page: the structure of
// its visible interactive elements (without free text or generated ids), its main headings, the open
// dialog and whether an alert or invalid field is shown. Content that changes between visits, such as
// list sizes, is collapsed, and `fingerprint.ignore` drops whole regions.
import { hash } from "./random.js";

// Ids generated by front-end frameworks change on every render (Ember, React, MUI, Radix, Headless UI…).
export const AUTO_ID_PATTERN = "^(ember\\d+|:r[0-9a-z]+:|react-[\\w-]+|mui-\\d+|radix-[\\w:-]+|headlessui-[\\w-]+|\\d+)$";

/** Origin, path and hash route of a URL; the query string only when requested. */
export function normalizeRoute(url, includeQuery) {
  const parsed = new URL(url);
  return `${parsed.origin}${parsed.pathname}${includeQuery ? parsed.search : ""}${parsed.hash}`;
}

/** Repeated consecutive descriptors (a list of similar rows) count once. */
export function collapse(descriptors) {
  return descriptors.filter((descriptor, index) => descriptor !== descriptors[index - 1]);
}

/** Abstraction of a scan: the list of features that identify the state. */
export function abstractionOf(scan, { includeQuery }) {
  return [
    `route:${normalizeRoute(scan.url, includeQuery)}`,
    ...scan.headings.map((heading) => `heading:${heading}`),
    ...(scan.dialog === null ? [] : [`dialog:${scan.dialog}`]),
    ...(scan.alerts ? ["alert"] : []),
    ...collapse(scan.descriptors),
  ];
}

export function fingerprintOf(abstraction) {
  return hash(abstraction);
}

/**
 * Jaccard similarity of two abstractions, 0 when their routes differ. Used to recognise a state when
 * replaying its path even if the application's data changed a little since it was discovered.
 */
export function similarity(a, b) {
  if (a[0] !== b[0]) return 0;
  const left = new Set(a);
  const right = new Set(b);
  const shared = [...left].filter((item) => right.has(item)).length;
  return shared / (left.size + right.size - shared);
}

export const SIMILAR_ENOUGH = 0.9;

/** Whether an observed page corresponds to a known state. */
export function matches(observed, state) {
  return observed.fingerprint === state.fingerprint || similarity(observed.abstraction, state.abstraction) >= SIMILAR_ENOUGH;
}
